install:
	gcc -o 1_badminton 1_badminton.c -lpthread -w
	gcc -o 2_voting 2_voting.c -lpthread -w
	gcc -o 3_threadmerge 3_threadmerge.c -lpthread -w
	gcc -o 3_normalmerge 3_normalmerge.c -lpthread -w
	gcc -o 3_concurrentmerge 3_concurrentmerge.c -lpthread -w
