install:
	gcc -o 1_badminton 1_badminton.c -lpthread
	gcc -o 3_threadmerge 3_threadmerge.c -lpthread
	gcc -o 3_normalmerge 3_normalmerge.c -lpthread
	gcc -o 3_concurrentmerge 3_concurrentmerge.c -lpthread
